### ISSUE TITLE
Não consta no repositório a planilha "Dados_MDI_PDE_2029.xlsx"

### ISSUE THREAD

**Issue by ClaudioSiervi** [equipesge/MDI_PDE_2029#1]
Conforme descrito no arquivo "Instruções Básicas.docx", a execução do MDI é feita a partir da planilha  "Dados_MDI_PDE_2029.xlsx", que também contém todas as premissas do modelo.

**Comment by equipesge** [comment]
Prezado Claudio,

O GitHub não permitiu o upload da planilha, devido ao tamanho do arquivo. A mesma pode ser baixada através do link: http://www.epe.gov.br/sites-pt/publicacoes-dados-abertos/publicacoes/PublicacoesArquivos/publicacao-423/topico-482/MDI-PDE-2029.zip
