### ISSUE TITLE
Erro ao executar o modelo 

### ISSUE THREAD

**Issue by ClaudioSiervi** [equipesge/MDI_PDE_2029#2]
Olá @equipesge, estou tentando rodar o projeto para entender um pouco sobre o plano decenal, mas estou recebendo um erro ao executar o modelo. 
```
Traceback (most recent call last):
  File "c:/Users/claudius/Documents/EPE_MDI_PDE_2029/Principal.py", line 19, in <module>
    control = Control(plan_dados = planilha, path = caminho, time = startDate);
  File "c:\Users\claudius\Documents\EPE_MDI_PDE_2029\Control.py", line 51, in __init__
  File "C:\Users\claudius\Documents\EPE_MDI_PDE_2029\venv\lib\site-packages\pyomo\opt\base\solvers.py", line 630, in solve
    _model.solutions.load_from(
  File "C:\Users\claudius\Documents\EPE_MDI_PDE_2029\venv\lib\site-packages\pyomo\core\base\PyomoModel.py", line 249, in load_from
    raise ValueError("Cannot load a SolverResults object "
ValueError: Cannot load a SolverResults object with bad status: error
```

 Imagino que este erro deve ser por que estou  usando algum pacote Python com versão diferente da que vocês usam, por isto, por favor, poderiam disponibilizar também um arquivo com as versões dos pacotes? Geralmente este arquivo é chamado de `requirements.txt` e pode ser obtido pelo comando: `pip freeze > requirements.txt`.

Obrigado pela atenção.

**Comment by equipesge** [comment]
Prezado Claudio,

Primeiramente, gostaríamos de pedir desculpas pela demora na resposta. Sua mensagem ficou perdida na nossa caixa de entrada.

Este erro que você obteve ocorre normalmente por problemas com o solver. Como podemos ver na mensagem de erro o status do SolverResults foi de erro. Qual solver você está utilizando? Aconselho você a ativar a opção tee do solver, que mostra no terminal o log de execução do solver. Basta descomentar o trecho da linha 50 do arquivo Control.py:

results = optsolver.solve(self.problema.modelo, load_solutions=True, symbolic_solver_labels=True, tee=True);

De qualquer forma, iremos incluir o arquivo requirements.txt no repositório.

Ficamos à disposição.
